# Generated by Django 4.2 on 2024-04-09 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_company_add_company_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='add',
            new_name='address',
        ),
    ]
